---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: chef_client_1219
    run_list:
      - recipe[influxdb-test::default]
    provisioner:
      require_chef_omnibus: 12.19.33
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: chef_client_1218
    run_list:
      - recipe[influxdb-test::default]
    provisioner:
      require_chef_omnibus: 12.18.31
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
